name: schooleverywhere
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.12
  http: ^0.13.4
  # flushbar: ^1.9.1
  firebase_core: ^1.7.0
  shared_preferences: ^2.0.8
  google_maps_flutter: ^2.0.11
  geolocator: ^7.7.0
  location: ^4.3.0
  font_awesome_flutter: ^9.1.0
  firebase_messaging: ^10.0.8
  flutter_spinkit: ^5.1.0
  expandable: ^5.0.1
  file_picker: ^4.1.4
  flutter_local_notifications: ^9.0.0
  flutter_uploader: ^3.0.0-beta.3
  dio: ^4.0.0
  flutter_downloader: ^1.7.1
  # downloads_path_provider: ^0.1.0
  path_provider: ^2.0.5
  random_string: ^2.3.1
  flutter_launcher_icons: ^0.9.2
  multiselect_formfield: ^0.1.6
  permission_handler: ^8.2.5
  firebase_database: ^8.0.0
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  firebase_core_web: ^1.1.0
  url_launcher_macos: ^2.0.2
  url_launcher_web: ^2.0.4
  zoom_widget: ^0.2.1
  fluttertoast: ^8.0.8
  # get_version: ^0.2.2
  # jitsi_meet: ^3.3.0
  badges: ^2.0.1
  video_player: ^2.2.5
  chewie: ^1.2.2
  audioplayers: ^0.20.1
  provider: ^5.0.0
  downloads_path_provider_28: ^0.1.2
  package_info_plus: ^1.3.0
  image_picker: ^0.8.4+3
  cached_network_image: ^3.1.0
  photo_view: ^0.13.0
  flutter_svg: ^0.23.0+1
  flutter_bloc: ^7.1.0
  just_audio: ^0.9.18
  record: ^3.0.2
  html2md: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "img/logo.png"
  image_path_android: "img/logo.png"
  image_path_ios: "img/logo.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/
    - assets/icons/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
